#!/usr/bin/ruby
require 'find'
require 'shellwords'

@errFile = "errors.log"
@STFile = "validSymbolTables.log"
open(@errFile, 'w') { |f| f.print "" }
open(@STFile, 'w')  { |f| f.print "" }

def runTests(testPath, isValid)
  testFiles = []
  Find.find(testPath) do |path|
    testFiles << (Shellwords.shellescape path) if path =~ /.*\.wacc$/
  end
  numTests = testFiles.length
  i = 1
  testFiles.each do |test|
    print "Running Test: #{i}/#{numTests}\r"
    testRun = `./grun -tree #{test[/src.*/]} 2>tmp`
    tmp = File.open("tmp", "r")
    if isValid && !File.zero?("tmp")
      error = "Running Test: #{File.basename test} \n Error(s): \n #{tmp.read}"
      open(@errFile, 'a') { |f| f.puts error}
    elsif !isValid && File.zero?("tmp")
      error = "Running Test: #{File.basename test} \n No Errors!"
      open(@errFile, 'a') { |f| f.puts error}
    end
    `rm tmp`
    i += 1
  end
  puts "\n"
end

def runCompile(testPath)
  testFiles = []
  Find.find(testPath) do |path|
    testFiles << (Shellwords.shellescape path) if path =~ /.*\.wacc$/
  end
  numTests = testFiles.length
  i = 1
  testFiles.each do |test|
    print "Running Test: #{i}/#{numTests}\r"
    testRun = `./compile #{test[/src.*/]} 2>tmp`
    tmp = File.open("tmp", "r")
    tmpContents = tmp.read
    if !(File.zero?("tmp") || tmpContents.strip.empty?)
      output = "Running Test: #{File.basename test} \n"
      output += "Output: \n\t#{testRun} \n"
      output += "Error(s): \n\t#{tmpContents}\n"
      output += "Finished Test."
      open(@STFile, 'a') { |f| f.puts output}
    end
    `rm tmp`
    i += 1
  end
  puts "\n\n"
end

testFolder = "#{Dir.pwd}/src/test/resources/examples/"
testFiles = []
Find.find(testFolder) do |path|
  testFiles << (Shellwords.shellescape path) if path =~ /.*\.wacc$/
end
# puts "Starting Valid tests..."
# open(@errFile, 'a') { |f| f.puts "Running Valid Tests:\n" }
# runTests(testFolder+"valid", true)
# puts "Finished Valid tests."
# puts "Starting Invalid tests..."
# open(@errFile, 'a') { |f| f.puts "Running Invalid Tests:\n" }
# runTests(testFolder+"invalid/syntaxErr", false)
# puts "Finished Invalid tests."
puts "Starting compile tests..."
runCompile(testFolder+"valid")
puts "Finished compile tests."
