#!/usr/bin/ruby
require 'find'
require 'shellwords'

@errFile = "errors.log"
@tmp = "tmp.log"

open(@errFile, 'w') { |f| f.print "" }

def runCompile(testPath, expectedExitCode)
  testFiles = []
  Find.find(testPath) {|path| testFiles << (Shellwords.shellescape path) if path =~ /.*\.wacc$/}
  numTests = testFiles.length
  i = 1
  hasErrored = 0
  isValid = expectedExitCode == 0;
  testFiles.each do |test|
    print "Running Test: #{i}/#{numTests}\r"
    testRun = `./compile #{test[/src.*/]} 2>#{@tmp}`

    tmp = File.open("#{@tmp}", "r")
    tmpContents = tmp.read
    output = "Running Test: #{File.basename test} \n"
    output += "Output: \n\t#{testRun} \n"

    if isValid && !(File.zero?("#{@tmp}") || tmpContents.strip.empty?)
      hasErrored += 1
      output += "Error(s): \n\t#{tmpContents}\n"
      output += "Finished Test."
      open(@errFile, 'a') { |f| f.puts output}
    elsif !isValid && (File.zero?("#{@tmp}") || tmpContents.strip.empty?)
      hasErrored += 1
      output += "Error(s): \n\t No Errors!\n"
      output += "Finished Test."
      open(@errFile, 'a') { |f| f.puts output}
    end

    actualExitCode = $?.exitstatus
    if (expectedExitCode != actualExitCode)
      exit_code_error = "Wrong exit code: #{actualExitCode}"
      open(@errFile, 'a') { |f| f.puts exit_code_error}
    end
    `rm #{@tmp}`
    i += 1
    break if hasErrored > 4
  end
  puts "\n\n"
end

testFolder = "#{Dir.pwd}/src/test/resources/examples/"

puts "Starting Valid Compile tests..."
runCompile(testFolder+"valid", 0)
puts "Finished tests."

puts "Starting Syntax Errors Compile tests..."
runCompile(testFolder+"invalid/syntaxErr", 100)
puts "Finished tests."

puts "Starting Semantic Errors Compile tests..."
runCompile(testFolder+"invalid/semanticErr", 200)
puts "Finished tests."
