#!/usr/bin/ruby

@file = ""

usage = "Usage: ./compile filename.wacc"

if ARGV[0]
  @file = "<" + ARGV[0]
end

def compile()
  result = `java -cp target/WACC-Compiler-0.2-BETA-jar-with-dependencies.jar wacc.WACCCompile #{@file}`
  puts result.strip!
  exit($?.exitstatus)
end

compile()
