#!/usr/bin/ruby
require 'find'
require 'shellwords'

errFile = "errors.log"

open(errFile, 'w') { |f| f.puts "" }

testFolder = "/Users/elliotgreenwood/Elliot\ Greenwood/I/Imperial/Year 2/WACC/wacc_examples/valid"
testFiles = []
Find.find(testFolder) do |path|
  testFiles << (Shellwords.shellescape path) if path =~ /.*\.wacc$/
end
puts "Starting tests..."
trees = []
numTests = testFiles.length
i = 1
testFiles.each do |test|
  print "Running Test: #{i}/#{numTests}\r"
  open(errFile, 'a') { |f| f.puts "Running Test: #{File.basename test}" }
  trees << `java -cp bin:lib/antlr-4.4-complete.jar Test < #{test} 2>>errors.log`
  open(errFile, 'a') { |f| f.puts "\n" }
  i += 1
end
puts "\n"
puts "Finished tests..."
